
server:
  port: 9001

spring:
  application:
    name: spring-db202507
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_study
    username: root
    password: mariadb
  jpa:
    # Hibernate가 MariaDB 10.6 버전 이상에 맞는 SQL 문법을 사용하게 하는 설정
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: create # sql 자동 생성
    properties:
      hibernate:
        format_sql: true # sql 세로로 써주는 옵션
    database: mysql

# MyBatis Setting
mybatis:
  # SQL file location
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spring.database.chap03


logging:
  level:
    root: INFO
    com.spring.database: DEBUG
    org:
      hibernate:
        SQL: debug